### PR TITLE
Added some 1.20 blocks and fixed breaking changes in 1.20.2 and 1.20.3

### PR DESCRIPTION
**Pull request by matej-darebnik**
I have changed loading of icons to work now that they are stored in individual files. I also made a fix for grass block, which was renamed to short_grass...

### CODE REVIEW

**Comment by matej-darebnik** [comment]
Apparently sign text is no longer in JSON format as of 1.20.3, so i fixed that too. This should also handle both sides of the sign, so the TODO list in #220 can maybe be updated....

**Comment by matej-darebnik** [comment]
I have also fixed cherry leaves tint and added cherry, bamboo and hanging signs:

Ingame:
Screenshot 2024-03-13 213609
Tectonicus:
Screenshot 2024-03-13 231334

**Comment by matej-darebnik** [comment]
piglin heads and decorated pots should now work:
Screenshot 2024-03-15 124605
Screenshot 2024-03-14 135559

**Comment by skoeven** [comment]
Great work, thank you!  I was dreading having to do the piglin heads and new signs so thanks for doing that, lol.  I appreciate you trying to maintain the backwards compatibility too, it sometimes makes for a lot more work but I like being able to render maps from old Minecraft versions.  Though that may have to change at some point if the code just gets too unreasonable to maintain.  Also thanks for all your previous work too! I haven't had time to do much on this in the last year so it's nice someone is still interested in Tectonicus.

**Pull request merged**
